using System;
using Gameplay.Levelling.PowerUps;
using static Gameplay.Levelling.SphereGrid.NodeFactory;

// ReSharper disable IdentifierTypo

namespace Gameplay.Levelling.SphereGrid;

public static class GridFactory
{
    public static SphereGrid Create(Action<IPowerUp> onUnlock)
    {
        var root = new Node(null, 0, 0);
        var projectilespeedup0 = ProjectileSpeedUp(1);
        var rangeup1 = RangeUp(1);
        var lifestealup2 = LifeStealUp(2);
        var rangeup3 = RangeUp(1);
        var speedup4 = SpeedUp(1);
        var experienceup5 = ExperienceUp(1);
        var attackspeedup6 = AttackSpeedUp(1);
        var projectilespeedup7 = ProjectileSpeedUp(1);
        var experienceup8 = ExperienceUp(1);
        var explodeonkillup9 = ExplodeOnKillUp(2);
        var critdamageup10 = CritDamageUp(1);
        var critchanceup11 = CritChanceUp(1);
        var damageup12 = DamageUp(1);
        var critchanceup13 = CritChanceUp(1);
        var experienceup14 = ExperienceUp(1);
        var critchanceup15 = CritChanceUp(1);
        var critdamageup16 = CritDamageUp(1);
        var pickupradiusup17 = PickupRadiusUp(1);
        var shotcountup18 = ShotCountUp(1);
        var maxhealthup19 = MaxHealthUp(1);
        var rangeup20 = RangeUp(1);
        var damageup21 = DamageUp(1);
        var rangeup22 = RangeUp(1);
        var speedup23 = SpeedUp(1);
        var critdamageup24 = CritDamageUp(1);
        var critchanceup25 = CritChanceUp(1);
        var experienceup26 = ExperienceUp(1);
        var rangeup27 = RangeUp(1);
        var shotcountup28 = ShotCountUp(1);
        var damageup29 = DamageUp(1);
        var pickupradiusup30 = PickupRadiusUp(1);
        var shotcountup31 = ShotCountUp(1);
        var experienceup32 = ExperienceUp(1);
        var attackspeedup33 = AttackSpeedUp(1);
        var maxhealthup34 = MaxHealthUp(1);
        var maxhealthup35 = MaxHealthUp(1);
        var experienceup36 = ExperienceUp(1);
        var attackspeedup37 = AttackSpeedUp(1);
        var projectilespeedup38 = ProjectileSpeedUp(1);
        var damageup39 = DamageUp(1);
        var critchanceup40 = CritChanceUp(1);
        var pierceup41 = PierceUp(1);
        var damageup42 = DamageUp(1);
        var rangeup43 = RangeUp(1);
        var experienceup44 = ExperienceUp(1);
        var speedup45 = SpeedUp(1);
        var maxhealthup46 = MaxHealthUp(1);
        var rangeup47 = RangeUp(1);
        var projectilespeedup48 = ProjectileSpeedUp(1);
        var pickupradiusup49 = PickupRadiusUp(1);
        var damageup50 = DamageUp(1);
        var projectilespeedup51 = ProjectileSpeedUp(1);
        var attackspeedup52 = AttackSpeedUp(1);
        var damageup53 = DamageUp(1);
        var experienceup54 = ExperienceUp(1);
        var damageup55 = DamageUp(3);
        var pickupradiusup56 = PickupRadiusUp(1);
        var rangeup57 = RangeUp(1);
        var speedup58 = SpeedUp(1);
        var attackspeedup59 = AttackSpeedUp(1);
        var pickupradiusup60 = PickupRadiusUp(3);
        var attackspeedup61 = AttackSpeedUp(1);
        var explodeonkillup62 = ExplodeOnKillUp(1);
        var pickupradiusup63 = PickupRadiusUp(1);
        var speedup64 = SpeedUp(1);
        var experienceup65 = ExperienceUp(1);
        var attackspeedup66 = AttackSpeedUp(1);
        var experienceup67 = ExperienceUp(1);
        var critchanceup68 = CritChanceUp(1);
        var projectilespeedup69 = ProjectileSpeedUp(1);
        var maxhealthup70 = MaxHealthUp(1);
        var damageup71 = DamageUp(2);
        var projectilespeedup72 = ProjectileSpeedUp(1);
        var maxhealthup73 = MaxHealthUp(1);
        var speedup74 = SpeedUp(1);
        var attackspeedup75 = AttackSpeedUp(1);
        var experienceup76 = ExperienceUp(1);
        var projectilespeedup77 = ProjectileSpeedUp(1);
        var maxhealthup78 = MaxHealthUp(3);
        var critchanceup79 = CritChanceUp(1);
        var speedup80 = SpeedUp(1);
        var rangeup81 = RangeUp(1);

        root.SetNeighbour(EdgeDirection.TopLeft, experienceup44);
        root.SetNeighbour(EdgeDirection.BottomRight, speedup45);
        root.SetNeighbour(EdgeDirection.TopRight, maxhealthup19);
        root.SetNeighbour(EdgeDirection.MiddleLeft, projectilespeedup0);
        root.SetNeighbour(EdgeDirection.MiddleRight, pickupradiusup49);
        root.SetNeighbour(EdgeDirection.BottomLeft, speedup4);
        projectilespeedup0.SetNeighbour(EdgeDirection.MiddleRight, root);
        projectilespeedup0.SetNeighbour(EdgeDirection.BottomLeft, experienceup65);
        rangeup1.SetNeighbour(EdgeDirection.MiddleRight, experienceup54);
        rangeup1.SetNeighbour(EdgeDirection.BottomLeft, projectilespeedup48);
        lifestealup2.SetNeighbour(EdgeDirection.BottomLeft, rangeup3);
        rangeup3.SetNeighbour(EdgeDirection.TopLeft, experienceup26);
        rangeup3.SetNeighbour(EdgeDirection.TopRight, lifestealup2);
        speedup4.SetNeighbour(EdgeDirection.BottomLeft, attackspeedup6);
        speedup4.SetNeighbour(EdgeDirection.TopRight, root);
        experienceup5.SetNeighbour(EdgeDirection.MiddleLeft, speedup45);
        experienceup5.SetNeighbour(EdgeDirection.MiddleRight, attackspeedup61);
        attackspeedup6.SetNeighbour(EdgeDirection.TopRight, speedup4);
        attackspeedup6.SetNeighbour(EdgeDirection.MiddleLeft, experienceup14);
        attackspeedup6.SetNeighbour(EdgeDirection.BottomLeft, projectilespeedup7);
        projectilespeedup7.SetNeighbour(EdgeDirection.TopRight, attackspeedup6);
        projectilespeedup7.SetNeighbour(EdgeDirection.BottomRight, experienceup8);
        experienceup8.SetNeighbour(EdgeDirection.TopLeft, projectilespeedup7);
        experienceup8.SetNeighbour(EdgeDirection.MiddleRight, critdamageup10);
        explodeonkillup9.SetNeighbour(EdgeDirection.BottomLeft, rangeup81);
        critdamageup10.SetNeighbour(EdgeDirection.MiddleLeft, experienceup8);
        critdamageup10.SetNeighbour(EdgeDirection.TopRight, critchanceup11);
        critchanceup11.SetNeighbour(EdgeDirection.BottomLeft, critdamageup10);
        critchanceup11.SetNeighbour(EdgeDirection.TopLeft, maxhealthup35);
        damageup12.SetNeighbour(EdgeDirection.TopRight, rangeup22);
        damageup12.SetNeighbour(EdgeDirection.MiddleLeft, pickupradiusup63);
        critchanceup13.SetNeighbour(EdgeDirection.MiddleLeft, pickupradiusup17);
        critchanceup13.SetNeighbour(EdgeDirection.TopLeft, shotcountup18);
        experienceup14.SetNeighbour(EdgeDirection.MiddleRight, attackspeedup6);
        experienceup14.SetNeighbour(EdgeDirection.MiddleLeft, critchanceup15);
        critchanceup15.SetNeighbour(EdgeDirection.MiddleRight, experienceup14);
        critchanceup15.SetNeighbour(EdgeDirection.BottomLeft, critdamageup16);
        critdamageup16.SetNeighbour(EdgeDirection.TopRight, critchanceup15);
        critdamageup16.SetNeighbour(EdgeDirection.BottomRight, pickupradiusup17);
        pickupradiusup17.SetNeighbour(EdgeDirection.TopLeft, critdamageup16);
        pickupradiusup17.SetNeighbour(EdgeDirection.MiddleRight, critchanceup13);
        shotcountup18.SetNeighbour(EdgeDirection.BottomRight, critchanceup13);
        maxhealthup19.SetNeighbour(EdgeDirection.BottomLeft, root);
        maxhealthup19.SetNeighbour(EdgeDirection.MiddleRight, rangeup20);
        maxhealthup19.SetNeighbour(EdgeDirection.TopLeft, experienceup32);
        rangeup20.SetNeighbour(EdgeDirection.MiddleLeft, maxhealthup19);
        rangeup20.SetNeighbour(EdgeDirection.TopRight, damageup21);
        damageup21.SetNeighbour(EdgeDirection.BottomLeft, rangeup20);
        damageup21.SetNeighbour(EdgeDirection.TopRight, speedup23);
        rangeup22.SetNeighbour(EdgeDirection.TopLeft, attackspeedup61);
        rangeup22.SetNeighbour(EdgeDirection.BottomLeft, damageup12);
        speedup23.SetNeighbour(EdgeDirection.BottomLeft, damageup21);
        speedup23.SetNeighbour(EdgeDirection.TopLeft, critchanceup25);
        speedup23.SetNeighbour(EdgeDirection.TopRight, rangeup27);
        critdamageup24.SetNeighbour(EdgeDirection.BottomLeft, experienceup26);
        critdamageup24.SetNeighbour(EdgeDirection.MiddleRight, critchanceup25);
        critchanceup25.SetNeighbour(EdgeDirection.MiddleLeft, critdamageup24);
        critchanceup25.SetNeighbour(EdgeDirection.BottomRight, speedup23);
        experienceup26.SetNeighbour(EdgeDirection.TopRight, critdamageup24);
        experienceup26.SetNeighbour(EdgeDirection.BottomRight, rangeup3);
        rangeup27.SetNeighbour(EdgeDirection.BottomLeft, speedup23);
        shotcountup28.SetNeighbour(EdgeDirection.MiddleLeft, speedup64);
        damageup29.SetNeighbour(EdgeDirection.MiddleLeft, pickupradiusup30);
        damageup29.SetNeighbour(EdgeDirection.BottomLeft, shotcountup31);
        pickupradiusup30.SetNeighbour(EdgeDirection.MiddleRight, damageup29);
        pickupradiusup30.SetNeighbour(EdgeDirection.BottomLeft, maxhealthup34);
        shotcountup31.SetNeighbour(EdgeDirection.TopRight, damageup29);
        experienceup32.SetNeighbour(EdgeDirection.BottomRight, maxhealthup19);
        experienceup32.SetNeighbour(EdgeDirection.TopLeft, attackspeedup33);
        attackspeedup33.SetNeighbour(EdgeDirection.TopLeft, maxhealthup34);
        attackspeedup33.SetNeighbour(EdgeDirection.BottomRight, experienceup32);
        maxhealthup34.SetNeighbour(EdgeDirection.TopRight, pickupradiusup30);
        maxhealthup34.SetNeighbour(EdgeDirection.BottomRight, attackspeedup33);
        maxhealthup35.SetNeighbour(EdgeDirection.BottomRight, critchanceup11);
        maxhealthup35.SetNeighbour(EdgeDirection.BottomLeft, explodeonkillup62);
        experienceup36.SetNeighbour(EdgeDirection.BottomRight, attackspeedup37);
        experienceup36.SetNeighbour(EdgeDirection.MiddleLeft, critchanceup79);
        attackspeedup37.SetNeighbour(EdgeDirection.MiddleRight, damageup42);
        attackspeedup37.SetNeighbour(EdgeDirection.TopLeft, experienceup36);
        attackspeedup37.SetNeighbour(EdgeDirection.BottomLeft, projectilespeedup38);
        projectilespeedup38.SetNeighbour(EdgeDirection.TopRight, attackspeedup37);
        projectilespeedup38.SetNeighbour(EdgeDirection.BottomRight, damageup39);
        damageup39.SetNeighbour(EdgeDirection.TopLeft, projectilespeedup38);
        damageup39.SetNeighbour(EdgeDirection.MiddleRight, critchanceup40);
        critchanceup40.SetNeighbour(EdgeDirection.MiddleLeft, damageup39);
        critchanceup40.SetNeighbour(EdgeDirection.TopLeft, pierceup41);
        pierceup41.SetNeighbour(EdgeDirection.BottomRight, critchanceup40);
        damageup42.SetNeighbour(EdgeDirection.BottomRight, rangeup43);
        damageup42.SetNeighbour(EdgeDirection.MiddleLeft, attackspeedup37);
        rangeup43.SetNeighbour(EdgeDirection.BottomRight, experienceup44);
        rangeup43.SetNeighbour(EdgeDirection.TopLeft, damageup42);
        experienceup44.SetNeighbour(EdgeDirection.BottomRight, root);
        experienceup44.SetNeighbour(EdgeDirection.TopLeft, rangeup43);
        speedup45.SetNeighbour(EdgeDirection.TopLeft, root);
        speedup45.SetNeighbour(EdgeDirection.MiddleRight, experienceup5);
        maxhealthup46.SetNeighbour(EdgeDirection.BottomLeft, attackspeedup59);
        maxhealthup46.SetNeighbour(EdgeDirection.TopLeft, rangeup47);
        rangeup47.SetNeighbour(EdgeDirection.BottomRight, maxhealthup46);
        rangeup47.SetNeighbour(EdgeDirection.BottomLeft, pickupradiusup60);
        projectilespeedup48.SetNeighbour(EdgeDirection.TopRight, rangeup1);
        projectilespeedup48.SetNeighbour(EdgeDirection.MiddleRight, damageup55);
        pickupradiusup49.SetNeighbour(EdgeDirection.MiddleRight, damageup50);
        pickupradiusup49.SetNeighbour(EdgeDirection.MiddleLeft, root);
        damageup50.SetNeighbour(EdgeDirection.MiddleLeft, pickupradiusup49);
        damageup50.SetNeighbour(EdgeDirection.MiddleRight, projectilespeedup51);
        projectilespeedup51.SetNeighbour(EdgeDirection.MiddleLeft, damageup50);
        projectilespeedup51.SetNeighbour(EdgeDirection.MiddleRight, attackspeedup52);
        attackspeedup52.SetNeighbour(EdgeDirection.MiddleLeft, projectilespeedup51);
        attackspeedup52.SetNeighbour(EdgeDirection.TopRight, damageup53);
        damageup53.SetNeighbour(EdgeDirection.BottomLeft, attackspeedup52);
        damageup53.SetNeighbour(EdgeDirection.BottomRight, pickupradiusup56);
        damageup53.SetNeighbour(EdgeDirection.TopLeft, experienceup54);
        experienceup54.SetNeighbour(EdgeDirection.BottomRight, damageup53);
        experienceup54.SetNeighbour(EdgeDirection.MiddleLeft, rangeup1);
        damageup55.SetNeighbour(EdgeDirection.MiddleLeft, projectilespeedup48);
        pickupradiusup56.SetNeighbour(EdgeDirection.TopLeft, damageup53);
        pickupradiusup56.SetNeighbour(EdgeDirection.BottomLeft, rangeup57);
        rangeup57.SetNeighbour(EdgeDirection.TopRight, pickupradiusup56);
        rangeup57.SetNeighbour(EdgeDirection.BottomRight, speedup58);
        speedup58.SetNeighbour(EdgeDirection.MiddleRight, attackspeedup59);
        speedup58.SetNeighbour(EdgeDirection.TopLeft, rangeup57);
        attackspeedup59.SetNeighbour(EdgeDirection.TopRight, maxhealthup46);
        attackspeedup59.SetNeighbour(EdgeDirection.MiddleLeft, speedup58);
        pickupradiusup60.SetNeighbour(EdgeDirection.TopRight, rangeup47);
        attackspeedup61.SetNeighbour(EdgeDirection.MiddleLeft, experienceup5);
        attackspeedup61.SetNeighbour(EdgeDirection.BottomRight, rangeup22);
        attackspeedup61.SetNeighbour(EdgeDirection.MiddleRight, projectilespeedup72);
        explodeonkillup62.SetNeighbour(EdgeDirection.TopRight, maxhealthup35);
        pickupradiusup63.SetNeighbour(EdgeDirection.MiddleRight, damageup12);
        pickupradiusup63.SetNeighbour(EdgeDirection.TopLeft, speedup64);
        speedup64.SetNeighbour(EdgeDirection.BottomRight, pickupradiusup63);
        speedup64.SetNeighbour(EdgeDirection.MiddleRight, shotcountup28);
        experienceup65.SetNeighbour(EdgeDirection.TopRight, projectilespeedup0);
        experienceup65.SetNeighbour(EdgeDirection.MiddleLeft, attackspeedup66);
        attackspeedup66.SetNeighbour(EdgeDirection.MiddleRight, experienceup65);
        attackspeedup66.SetNeighbour(EdgeDirection.MiddleLeft, critchanceup68);
        experienceup67.SetNeighbour(EdgeDirection.TopLeft, maxhealthup70);
        experienceup67.SetNeighbour(EdgeDirection.MiddleRight, damageup71);
        critchanceup68.SetNeighbour(EdgeDirection.MiddleRight, attackspeedup66);
        critchanceup68.SetNeighbour(EdgeDirection.TopLeft, projectilespeedup69);
        projectilespeedup69.SetNeighbour(EdgeDirection.BottomRight, critchanceup68);
        projectilespeedup69.SetNeighbour(EdgeDirection.TopRight, maxhealthup70);
        maxhealthup70.SetNeighbour(EdgeDirection.BottomLeft, projectilespeedup69);
        maxhealthup70.SetNeighbour(EdgeDirection.BottomRight, experienceup67);
        damageup71.SetNeighbour(EdgeDirection.MiddleLeft, experienceup67);
        projectilespeedup72.SetNeighbour(EdgeDirection.MiddleLeft, attackspeedup61);
        projectilespeedup72.SetNeighbour(EdgeDirection.BottomRight, maxhealthup73);
        maxhealthup73.SetNeighbour(EdgeDirection.TopLeft, projectilespeedup72);
        maxhealthup73.SetNeighbour(EdgeDirection.BottomLeft, speedup74);
        speedup74.SetNeighbour(EdgeDirection.TopRight, maxhealthup73);
        speedup74.SetNeighbour(EdgeDirection.BottomRight, attackspeedup75);
        attackspeedup75.SetNeighbour(EdgeDirection.MiddleRight, experienceup76);
        attackspeedup75.SetNeighbour(EdgeDirection.TopLeft, speedup74);
        experienceup76.SetNeighbour(EdgeDirection.MiddleLeft, attackspeedup75);
        experienceup76.SetNeighbour(EdgeDirection.TopRight, projectilespeedup77);
        projectilespeedup77.SetNeighbour(EdgeDirection.BottomLeft, experienceup76);
        projectilespeedup77.SetNeighbour(EdgeDirection.MiddleLeft, maxhealthup78);
        maxhealthup78.SetNeighbour(EdgeDirection.MiddleRight, projectilespeedup77);
        critchanceup79.SetNeighbour(EdgeDirection.MiddleRight, experienceup36);
        critchanceup79.SetNeighbour(EdgeDirection.BottomLeft, speedup80);
        speedup80.SetNeighbour(EdgeDirection.TopRight, critchanceup79);
        speedup80.SetNeighbour(EdgeDirection.BottomRight, rangeup81);
        rangeup81.SetNeighbour(EdgeDirection.TopLeft, speedup80);
        rangeup81.SetNeighbour(EdgeDirection.TopRight, explodeonkillup9);

        return new SphereGrid(root)
        {
            OnUnlock = onUnlock,
        };
    }
}