using System;
using Gameplay.Levelling.PowerUps;

// ReSharper disable IdentifierTypo

namespace Gameplay.Levelling.SphereGrid;

public static class GridFactory
{
    public static SphereGrid Create(Action<IPowerUp> onUnlock)
    {
        var root = new Node(null, 0, 0);
        var projectilespeedup0 = NodeFactory.ProjectileSpeedUp(1);
        var speedup1 = NodeFactory.SpeedUp(1);
        var attackspeedup2 = NodeFactory.AttackSpeedUp(1);
        var projectilespeedup3 = NodeFactory.ProjectileSpeedUp(1);
        var experienceup4 = NodeFactory.ExperienceUp(1);
        var critchanceup5 = NodeFactory.CritChanceUp(2);
        var critdamageup6 = NodeFactory.CritDamageUp(1);
        var critchanceup7 = NodeFactory.CritChanceUp(1);
        var pickupradiusup8 = NodeFactory.PickupRadiusUp(1);
        var speedup9 = NodeFactory.SpeedUp(1);
        var experienceup10 = NodeFactory.ExperienceUp(1);
        var critchanceup11 = NodeFactory.CritChanceUp(1);
        var critdamageup12 = NodeFactory.CritDamageUp(1);
        var pickupradiusup13 = NodeFactory.PickupRadiusUp(1);
        var shotcountup14 = NodeFactory.ShotCountUp(1);
        var maxhealthup15 = NodeFactory.MaxHealthUp(1);
        var rangeup16 = NodeFactory.RangeUp(1);
        var attackspeedup17 = NodeFactory.AttackSpeedUp(1);
        var lifestealup18 = NodeFactory.LifeStealUp(1);
        var speedup19 = NodeFactory.SpeedUp(1);
        var damageup20 = NodeFactory.DamageUp(1);
        var rangeup21 = NodeFactory.RangeUp(1);
        var critchanceup22 = NodeFactory.CritChanceUp(1);
        var damageup23 = NodeFactory.DamageUp(1);
        var speedup24 = NodeFactory.SpeedUp(1);
        var pickupradiusup25 = NodeFactory.PickupRadiusUp(1);
        var critchanceup26 = NodeFactory.CritChanceUp(1);
        var attackspeedup27 = NodeFactory.AttackSpeedUp(1);
        var maxhealthup28 = NodeFactory.MaxHealthUp(1);
        var experienceup29 = NodeFactory.ExperienceUp(1);
        var experienceup30 = NodeFactory.ExperienceUp(1);
        var attackspeedup31 = NodeFactory.AttackSpeedUp(1);
        var damageup32 = NodeFactory.DamageUp(1);
        var rangeup33 = NodeFactory.RangeUp(1);
        var experienceup34 = NodeFactory.ExperienceUp(1);
        var speedup35 = NodeFactory.SpeedUp(1);
        var pickupradiusup36 = NodeFactory.PickupRadiusUp(1);
        var damageup37 = NodeFactory.DamageUp(1);
        var projectilespeedup38 = NodeFactory.ProjectileSpeedUp(1);
        var attackspeedup39 = NodeFactory.AttackSpeedUp(1);
        var damageup40 = NodeFactory.DamageUp(1);
        var pickupradiusup41 = NodeFactory.PickupRadiusUp(1);
        var rangeup42 = NodeFactory.RangeUp(1);
        var speedup43 = NodeFactory.SpeedUp(1);
        var attackspeedup44 = NodeFactory.AttackSpeedUp(1);
        var damageup45 = NodeFactory.DamageUp(3);
        var attackspeedup46 = NodeFactory.AttackSpeedUp(1);
        var projectilespeedup47 = NodeFactory.ProjectileSpeedUp(1);
        var damageup48 = NodeFactory.DamageUp(1);
        var critchanceup49 = NodeFactory.CritChanceUp(1);
        var pierceup50 = NodeFactory.PierceUp(1);
        var experienceup51 = NodeFactory.ExperienceUp(1);
        var damageup52 = NodeFactory.DamageUp(2);
        var attackspeedup53 = NodeFactory.AttackSpeedUp(1);
        var lifestealup54 = NodeFactory.LifeStealUp(2);

        root.SetNeighbour(EdgeDirection.TopLeft, experienceup34);
        root.SetNeighbour(EdgeDirection.BottomRight, speedup35);
        root.SetNeighbour(EdgeDirection.TopRight, maxhealthup15);
        root.SetNeighbour(EdgeDirection.MiddleLeft, projectilespeedup0);
        projectilespeedup0.SetNeighbour(EdgeDirection.MiddleRight, root);
        projectilespeedup0.SetNeighbour(EdgeDirection.BottomRight, speedup1);
        speedup1.SetNeighbour(EdgeDirection.TopLeft, projectilespeedup0);
        speedup1.SetNeighbour(EdgeDirection.BottomLeft, attackspeedup2);
        attackspeedup2.SetNeighbour(EdgeDirection.TopRight, speedup1);
        attackspeedup2.SetNeighbour(EdgeDirection.MiddleLeft, experienceup10);
        attackspeedup2.SetNeighbour(EdgeDirection.BottomLeft, projectilespeedup3);
        projectilespeedup3.SetNeighbour(EdgeDirection.TopRight, attackspeedup2);
        projectilespeedup3.SetNeighbour(EdgeDirection.BottomRight, experienceup4);
        experienceup4.SetNeighbour(EdgeDirection.TopLeft, projectilespeedup3);
        experienceup4.SetNeighbour(EdgeDirection.MiddleRight, critdamageup6);
        experienceup4.SetNeighbour(EdgeDirection.BottomLeft, critchanceup5);
        critchanceup5.SetNeighbour(EdgeDirection.TopRight, experienceup4);
        critdamageup6.SetNeighbour(EdgeDirection.MiddleLeft, experienceup4);
        critdamageup6.SetNeighbour(EdgeDirection.TopRight, critchanceup7);
        critchanceup7.SetNeighbour(EdgeDirection.BottomLeft, critdamageup6);
        critchanceup7.SetNeighbour(EdgeDirection.BottomRight, pickupradiusup8);
        pickupradiusup8.SetNeighbour(EdgeDirection.TopLeft, critchanceup7);
        pickupradiusup8.SetNeighbour(EdgeDirection.MiddleRight, speedup9);
        speedup9.SetNeighbour(EdgeDirection.MiddleLeft, pickupradiusup8);
        experienceup10.SetNeighbour(EdgeDirection.MiddleRight, attackspeedup2);
        experienceup10.SetNeighbour(EdgeDirection.MiddleLeft, critchanceup11);
        critchanceup11.SetNeighbour(EdgeDirection.MiddleRight, experienceup10);
        critchanceup11.SetNeighbour(EdgeDirection.BottomLeft, critdamageup12);
        critdamageup12.SetNeighbour(EdgeDirection.TopRight, critchanceup11);
        critdamageup12.SetNeighbour(EdgeDirection.BottomRight, pickupradiusup13);
        pickupradiusup13.SetNeighbour(EdgeDirection.TopLeft, critdamageup12);
        pickupradiusup13.SetNeighbour(EdgeDirection.TopRight, shotcountup14);
        shotcountup14.SetNeighbour(EdgeDirection.BottomLeft, pickupradiusup13);
        maxhealthup15.SetNeighbour(EdgeDirection.BottomLeft, root);
        maxhealthup15.SetNeighbour(EdgeDirection.MiddleRight, rangeup16);
        rangeup16.SetNeighbour(EdgeDirection.MiddleLeft, maxhealthup15);
        rangeup16.SetNeighbour(EdgeDirection.TopRight, attackspeedup17);
        attackspeedup17.SetNeighbour(EdgeDirection.BottomLeft, rangeup16);
        attackspeedup17.SetNeighbour(EdgeDirection.TopLeft, lifestealup18);
        lifestealup18.SetNeighbour(EdgeDirection.BottomRight, attackspeedup17);
        lifestealup18.SetNeighbour(EdgeDirection.MiddleRight, speedup19);
        speedup19.SetNeighbour(EdgeDirection.MiddleLeft, lifestealup18);
        speedup19.SetNeighbour(EdgeDirection.TopLeft, damageup20);
        damageup20.SetNeighbour(EdgeDirection.BottomRight, speedup19);
        damageup20.SetNeighbour(EdgeDirection.MiddleRight, rangeup21);
        damageup20.SetNeighbour(EdgeDirection.MiddleLeft, attackspeedup53);
        rangeup21.SetNeighbour(EdgeDirection.MiddleLeft, damageup20);
        rangeup21.SetNeighbour(EdgeDirection.TopRight, critchanceup22);
        critchanceup22.SetNeighbour(EdgeDirection.BottomLeft, rangeup21);
        critchanceup22.SetNeighbour(EdgeDirection.MiddleLeft, damageup23);
        damageup23.SetNeighbour(EdgeDirection.MiddleRight, critchanceup22);
        damageup23.SetNeighbour(EdgeDirection.MiddleLeft, speedup24);
        speedup24.SetNeighbour(EdgeDirection.MiddleRight, damageup23);
        speedup24.SetNeighbour(EdgeDirection.MiddleLeft, pickupradiusup25);
        pickupradiusup25.SetNeighbour(EdgeDirection.BottomLeft, critchanceup26);
        pickupradiusup25.SetNeighbour(EdgeDirection.MiddleRight, speedup24);
        critchanceup26.SetNeighbour(EdgeDirection.BottomLeft, attackspeedup27);
        critchanceup26.SetNeighbour(EdgeDirection.TopRight, pickupradiusup25);
        attackspeedup27.SetNeighbour(EdgeDirection.TopLeft, maxhealthup28);
        attackspeedup27.SetNeighbour(EdgeDirection.TopRight, critchanceup26);
        maxhealthup28.SetNeighbour(EdgeDirection.MiddleLeft, experienceup29);
        maxhealthup28.SetNeighbour(EdgeDirection.BottomRight, attackspeedup27);
        experienceup29.SetNeighbour(EdgeDirection.MiddleLeft, experienceup30);
        experienceup29.SetNeighbour(EdgeDirection.MiddleRight, maxhealthup28);
        experienceup30.SetNeighbour(EdgeDirection.BottomRight, attackspeedup31);
        experienceup30.SetNeighbour(EdgeDirection.MiddleRight, experienceup29);
        attackspeedup31.SetNeighbour(EdgeDirection.MiddleRight, damageup32);
        attackspeedup31.SetNeighbour(EdgeDirection.TopLeft, experienceup30);
        attackspeedup31.SetNeighbour(EdgeDirection.BottomLeft, projectilespeedup47);
        damageup32.SetNeighbour(EdgeDirection.BottomRight, rangeup33);
        damageup32.SetNeighbour(EdgeDirection.MiddleLeft, attackspeedup31);
        rangeup33.SetNeighbour(EdgeDirection.BottomRight, experienceup34);
        rangeup33.SetNeighbour(EdgeDirection.TopLeft, damageup32);
        experienceup34.SetNeighbour(EdgeDirection.BottomRight, root);
        experienceup34.SetNeighbour(EdgeDirection.TopLeft, rangeup33);
        speedup35.SetNeighbour(EdgeDirection.TopLeft, root);
        speedup35.SetNeighbour(EdgeDirection.TopRight, pickupradiusup36);
        pickupradiusup36.SetNeighbour(EdgeDirection.BottomLeft, speedup35);
        pickupradiusup36.SetNeighbour(EdgeDirection.MiddleRight, damageup37);
        damageup37.SetNeighbour(EdgeDirection.MiddleLeft, pickupradiusup36);
        damageup37.SetNeighbour(EdgeDirection.BottomLeft, attackspeedup46);
        damageup37.SetNeighbour(EdgeDirection.MiddleRight, projectilespeedup38);
        projectilespeedup38.SetNeighbour(EdgeDirection.MiddleLeft, damageup37);
        projectilespeedup38.SetNeighbour(EdgeDirection.MiddleRight, attackspeedup39);
        attackspeedup39.SetNeighbour(EdgeDirection.MiddleLeft, projectilespeedup38);
        attackspeedup39.SetNeighbour(EdgeDirection.TopRight, damageup40);
        damageup40.SetNeighbour(EdgeDirection.BottomLeft, attackspeedup39);
        damageup40.SetNeighbour(EdgeDirection.BottomRight, pickupradiusup41);
        damageup40.SetNeighbour(EdgeDirection.TopLeft, experienceup51);
        pickupradiusup41.SetNeighbour(EdgeDirection.TopLeft, damageup40);
        pickupradiusup41.SetNeighbour(EdgeDirection.BottomLeft, rangeup42);
        rangeup42.SetNeighbour(EdgeDirection.TopRight, pickupradiusup41);
        rangeup42.SetNeighbour(EdgeDirection.BottomRight, speedup43);
        speedup43.SetNeighbour(EdgeDirection.MiddleRight, attackspeedup44);
        speedup43.SetNeighbour(EdgeDirection.TopLeft, rangeup42);
        attackspeedup44.SetNeighbour(EdgeDirection.TopLeft, damageup45);
        attackspeedup44.SetNeighbour(EdgeDirection.MiddleLeft, speedup43);
        damageup45.SetNeighbour(EdgeDirection.BottomRight, attackspeedup44);
        attackspeedup46.SetNeighbour(EdgeDirection.TopRight, damageup37);
        projectilespeedup47.SetNeighbour(EdgeDirection.TopRight, attackspeedup31);
        projectilespeedup47.SetNeighbour(EdgeDirection.BottomRight, damageup48);
        damageup48.SetNeighbour(EdgeDirection.TopLeft, projectilespeedup47);
        damageup48.SetNeighbour(EdgeDirection.MiddleRight, critchanceup49);
        critchanceup49.SetNeighbour(EdgeDirection.MiddleLeft, damageup48);
        critchanceup49.SetNeighbour(EdgeDirection.TopLeft, pierceup50);
        pierceup50.SetNeighbour(EdgeDirection.BottomRight, critchanceup49);
        experienceup51.SetNeighbour(EdgeDirection.BottomRight, damageup40);
        experienceup51.SetNeighbour(EdgeDirection.BottomLeft, damageup52);
        damageup52.SetNeighbour(EdgeDirection.TopRight, experienceup51);
        attackspeedup53.SetNeighbour(EdgeDirection.MiddleRight, damageup20);
        attackspeedup53.SetNeighbour(EdgeDirection.BottomLeft, lifestealup54);
        lifestealup54.SetNeighbour(EdgeDirection.TopRight, attackspeedup53);

        return new SphereGrid(root)
        {
            OnUnlock = onUnlock
        };
    }
}